"""add_college_domain_to_users_and_listings

Revision ID: de85009e175b
Revises: ea48f6852797
Create Date: 2026-02-21 06:22:04.709131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de85009e175b'
down_revision: Union[str, None] = 'ea48f6852797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('college_domain', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_listings_college_domain'), 'listings', ['college_domain'], unique=False)
    op.add_column('users', sa.Column('college_domain', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_college_domain'), 'users', ['college_domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_college_domain'), table_name='users')
    op.drop_column('users', 'college_domain')
    op.drop_index(op.f('ix_listings_college_domain'), table_name='listings')
    op.drop_column('listings', 'college_domain')
    # ### end Alembic commands ###
